### ISSUE TITLE
[feature request] Integration for .csv files 

### ISSUE THREAD

**Issue by EsporosRubeos** [Kartoffel0/Kindle2Anki#3]
Hello, I found your script fantastic.

I wanted to use it to create Mandarin cards from a .csv file. I can create the cards from the + feature in Yomichan but I wanted to create a vocab deck with 5000+ words, impossible to do by hand. I have my vocab list in a .csv file and was wondering how hard it's to tweak your script to make it use .csv files. 
I think that compatibility with Mandarin is not an issue, because I can already create Mandarin cards from the Yomichan extension. Is that right?
About the audio files, can they be requested from the Yomichan dictionaries as well? 
Also, I'm studying python (but I'm still at a basic level) so if you don't have time and think that feature is not that advanced, could you give me some instructions to implement it?

Thank you so much.

**Comment by Kartoffel0** [comment]
The entire script is centered around Kindle's vocabdb, so I really don't think it's worth it to implement some kinda of csv support on Kindle2Anki. 
Here's a modified version of the script that does support it tho, just rename it from .txt to .py and you should be able to use it
[csv2anki.txt](https://github.com/Kartoffel0/Kindle2Anki/files/10246584/csv2anki.txt)
